Add solution for 2017-day4
Kushagra-0801/Advent-Of-Code pull request #89
Opened 2019-10-03 06:03 UTC by Glyphack

Closes https://github.com/Kushagra-0801/Advent-Of-Code/issues/57

2019-10-03 10:10 UTC, Kushagra-0801 requested changes
Please make the given changes

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 1.py
> +    for passphrase in passphrases:
no need to store all the passphrases in a list
Just process them as they come

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 1.py
> +print(unique_passphrases_count)
Add a new line

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 2.py
> +        passphrases.append(list(line.split()))
Same thing. No need for this

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 2.py
> +import itertools
unused import

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 2.py
> +        passphrase = list(map(lambda x: ('').join(sorted(list(x))), passphrase_list))
It is preferable to use a `list comprehension` than calling `list` on `map`.
Also, sorted works fine on strings, no need to convert it to a list. Though the return object is a list and needs to be joined

2019-10-03 10:10 UTC, Kushagra-0801 commented on 2017/Day 4 - 2.py
> +
Unnecessary vertical whitespace

2019-10-04 06:54 UTC, namannimmo10 approved these changes
LGTM @Kushagra-0801. Thanks for your contribution. @Glyphack

2019-10-04 06:54 UTC, merged